import { Property } from "@shared/schema";

// Mock property data with real NZ addresses for development/demo purposes
export const mockProperties: Omit<Property, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    userId: "demo-user",
    title: "Modern Family Home",
    address: "123 Queen Street, Auckland Central",
    suburb: "Auckland Central",
    price: "$1,250,000",
    bedrooms: 4,
    bathrooms: 2,
    floorArea: 180,
    landArea: 450,
    carSpaces: 2,
    propertyType: "residential",
    lotNumber: "Lot 15 DP 456789",
    certificateOfTitle: "CT 456789/123",
    hideCertificateOfTitle: false,
    zoning: "Residential Mixed Use",
    yearBuilt: 2018,
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Stunning modern family home with open plan living and city views",
    views: 147,
    likes: 23,
    saves: 8,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Luxury Apartment",
    address: "89 The Terrace, Wellington Central",
    suburb: "Wellington Central",
    price: "$950,000",
    bedrooms: 2,
    bathrooms: 2,
    floorArea: 95,
    landArea: 0,
    carSpaces: 1,
    propertyType: "residential",
    lotNumber: "Lot 3 DP 567890",
    certificateOfTitle: "CT 567890/456",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2020,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Executive apartment with harbour views and premium finishes",
    views: 89,
    likes: 15,
    saves: 5,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Character Villa",
    address: "456 Colombo Street, Christchurch",
    suburb: "Sydenham",
    price: "$720,000",
    bedrooms: 3,
    bathrooms: 2,
    floorArea: 150,
    landArea: 600,
    carSpaces: 1,
    propertyType: "residential",
    lotNumber: "Lot 8 DP 678901",
    certificateOfTitle: "CT 678901/789",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 1925,
    imageUrl: "https://images.unsplash.com/photo-1449844908441-8829872d2607?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Beautifully restored villa with period features and modern amenities",
    views: 203,
    likes: 31,
    saves: 12,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Beachfront Apartment",
    address: "234 Marine Parade, Mount Maunganui",
    suburb: "Mount Maunganui",
    price: "$1,150,000",
    bedrooms: 3,
    bathrooms: 2,
    floorArea: 120,
    landArea: 0,
    carSpaces: 1,
    propertyType: "residential",
    lotNumber: "Lot 12 DP 789012",
    certificateOfTitle: "CT 789012/234",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2019,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Stunning beachfront location with panoramic ocean views",
    views: 298,
    likes: 45,
    saves: 18,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Student Rental",
    address: "78 Castle Street, Dunedin",
    suburb: "North Dunedin",
    price: "$480/week",
    bedrooms: 4,
    bathrooms: 2,
    floorArea: 140,
    landArea: 400,
    carSpaces: 2,
    propertyType: "rental",
    lotNumber: "Lot 13 DP 890123",
    certificateOfTitle: "CT 890123/567",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2005,
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Perfect for students, close to University of Otago",
    views: 156,
    likes: 22,
    saves: 9,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Commercial Office",
    address: "67 High Street, Auckland",
    suburb: "Auckland Central",
    price: "$2,500,000",
    bedrooms: 0,
    bathrooms: 4,
    floorArea: 450,
    landArea: 0,
    carSpaces: 5,
    propertyType: "commercial",
    lotNumber: "Lot 1 DP 012345",
    certificateOfTitle: "CT 012345/678",
    hideCertificateOfTitle: false,
    zoning: "Commercial",
    yearBuilt: 2010,
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Prime commercial space in the heart of Auckland CBD",
    views: 67,
    likes: 8,
    saves: 3,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Family Home",
    address: "145 Papanui Road, Christchurch",
    suburb: "Papanui",
    price: "$650,000",
    bedrooms: 4,
    bathrooms: 2,
    floorArea: 170,
    landArea: 650,
    carSpaces: 2,
    propertyType: "residential",
    lotNumber: "Lot 10 DP 123789",
    certificateOfTitle: "CT 123789/456",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2000,
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Spacious family home with large backyard and double garage",
    views: 134,
    likes: 19,
    saves: 7,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Penthouse Suite",
    address: "56 Albert Street, Auckland",
    suburb: "Auckland Central",
    price: "$2,200,000",
    bedrooms: 3,
    bathrooms: 3,
    floorArea: 220,
    landArea: 0,
    carSpaces: 2,
    propertyType: "residential",
    lotNumber: "Lot 14 DP 456123",
    certificateOfTitle: "CT 456123/789",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2022,
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Luxury penthouse with 360-degree city and harbour views",
    views: 87,
    likes: 41,
    saves: 19,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Townhouse",
    address: "23 Riccarton Road, Christchurch",
    suburb: "Riccarton",
    price: "$580,000",
    bedrooms: 3,
    bathrooms: 2,
    floorArea: 130,
    landArea: 200,
    carSpaces: 1,
    propertyType: "residential",
    lotNumber: "Lot 7 DP 789456",
    certificateOfTitle: "CT 789456/123",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2016,
    imageUrl: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Modern townhouse in popular Riccarton location",
    views: 112,
    likes: 16,
    saves: 6,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Retail Space",
    address: "89 Cuba Street, Wellington",
    suburb: "Te Aro",
    price: "$550,000",
    bedrooms: 0,
    bathrooms: 1,
    floorArea: 80,
    landArea: 0,
    carSpaces: 0,
    propertyType: "commercial",
    lotNumber: "Lot 2 DP 567123",
    certificateOfTitle: "CT 567123/890",
    hideCertificateOfTitle: false,
    zoning: "Commercial",
    yearBuilt: 1980,
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Prime retail opportunity on famous Cuba Street",
    views: 95,
    likes: 12,
    saves: 4,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Beach House",
    address: "12 Ocean View Road, Raglan",
    suburb: "Raglan",
    price: "$890,000",
    bedrooms: 3,
    bathrooms: 2,
    floorArea: 140,
    landArea: 800,
    carSpaces: 2,
    propertyType: "residential",
    lotNumber: "Lot 5 DP 234890",
    certificateOfTitle: "CT 234890/567",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 1990,
    imageUrl: "https://images.unsplash.com/photo-1520637736862-4d197d17c46a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Charming beach house just steps from famous surf breaks",
    views: 245,
    likes: 38,
    saves: 15,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "City Apartment",
    address: "45 Willis Street, Wellington",
    suburb: "Wellington Central",
    price: "$620,000",
    bedrooms: 1,
    bathrooms: 1,
    floorArea: 55,
    landArea: 0,
    carSpaces: 0,
    propertyType: "residential",
    lotNumber: "Lot 8 DP 345123",
    certificateOfTitle: "CT 345123/456",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2015,
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Compact city living in the heart of Wellington",
    views: 78,
    likes: 11,
    saves: 4,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Warehouse Conversion",
    address: "123 Karangahape Road, Auckland",
    suburb: "Auckland Central",
    price: "$850,000",
    bedrooms: 2,
    bathrooms: 1,
    floorArea: 160,
    landArea: 0,
    carSpaces: 1,
    propertyType: "residential",
    lotNumber: "Lot 6 DP 678234",
    certificateOfTitle: "CT 678234/789",
    hideCertificateOfTitle: false,
    zoning: "Mixed Use",
    yearBuilt: 1920,
    imageUrl: "https://images.unsplash.com/photo-1560448075-bb485b067938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Unique warehouse conversion with soaring ceilings and character features",
    views: 189,
    likes: 28,
    saves: 12,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Suburban Home",
    address: "67 Lincoln Road, Henderson",
    suburb: "Henderson",
    price: "$780,000",
    bedrooms: 3,
    bathrooms: 2,
    floorArea: 140,
    landArea: 600,
    carSpaces: 2,
    propertyType: "residential",
    lotNumber: "Lot 11 DP 456789",
    certificateOfTitle: "CT 456789/012",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2008,
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Well-maintained family home in quiet suburban street",
    views: 123,
    likes: 17,
    saves: 6,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Office Lease",
    address: "12 Customs Street, Auckland",
    suburb: "Auckland Central",
    price: "$8,500/month",
    bedrooms: 0,
    bathrooms: 2,
    floorArea: 200,
    landArea: 0,
    carSpaces: 3,
    propertyType: "lease",
    lotNumber: "Lot 7 DP 789123",
    certificateOfTitle: "CT 789123/456",
    hideCertificateOfTitle: false,
    zoning: "Commercial",
    yearBuilt: 2015,
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Premium office space with harbour views available for lease",
    views: 56,
    likes: 7,
    saves: 2,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Luxury Villa",
    address: "45 Orakei Road, Auckland",
    suburb: "Orakei",
    price: "$3,500,000",
    bedrooms: 5,
    bathrooms: 4,
    floorArea: 350,
    landArea: 1200,
    carSpaces: 4,
    propertyType: "residential",
    lotNumber: "Lot 1 DP 123456",
    certificateOfTitle: "CT 123456/789",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2020,
    imageUrl: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Architectural masterpiece with panoramic harbour views",
    views: 312,
    likes: 89,
    saves: 34,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Student Flat",
    address: "234 George Street, Dunedin",
    suburb: "North Dunedin",
    price: "$420/week",
    bedrooms: 5,
    bathrooms: 2,
    floorArea: 160,
    landArea: 300,
    carSpaces: 1,
    propertyType: "rental",
    lotNumber: "Lot 9 DP 567234",
    certificateOfTitle: "CT 567234/890",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 1995,
    imageUrl: "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Large student flat walking distance to university",
    views: 167,
    likes: 24,
    saves: 8,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Country Estate",
    address: "789 Clevedon Road, Clevedon",
    suburb: "Clevedon",
    price: "$2,800,000",
    bedrooms: 4,
    bathrooms: 3,
    floorArea: 280,
    landArea: 5000,
    carSpaces: 3,
    propertyType: "residential",
    lotNumber: "Lot 3 DP 678345",
    certificateOfTitle: "CT 678345/012",
    hideCertificateOfTitle: false,
    zoning: "Rural Residential",
    yearBuilt: 2012,
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Stunning country estate with rolling hills and mature gardens",
    views: 98,
    likes: 43,
    saves: 21,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Industrial Unit",
    address: "567 Great South Road, Auckland",
    suburb: "Otahuhu",
    price: "$650,000",
    bedrooms: 0,
    bathrooms: 1,
    floorArea: 300,
    landArea: 800,
    carSpaces: 6,
    propertyType: "commercial",
    lotNumber: "Lot 15 DP 789567",
    certificateOfTitle: "CT 789567/234",
    hideCertificateOfTitle: false,
    zoning: "Industrial",
    yearBuilt: 2005,
    imageUrl: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Modern industrial unit with good truck access",
    views: 45,
    likes: 6,
    saves: 2,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  },
  {
    userId: "demo-user",
    title: "Coastal Home",
    address: "89 Beach Road, Orewa",
    suburb: "Orewa",
    price: "$1,650,000",
    bedrooms: 4,
    bathrooms: 3,
    floorArea: 200,
    landArea: 700,
    carSpaces: 2,
    propertyType: "residential",
    lotNumber: "Lot 12 DP 234567",
    certificateOfTitle: "CT 234567/890",
    hideCertificateOfTitle: false,
    zoning: "Residential",
    yearBuilt: 2017,
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    description: "Modern coastal home with direct beach access",
    views: 201,
    likes: 36,
    saves: 14,
    isLinzValidated: true,
    selfDeclaration: true,
    isActive: true,
    additionalImages: []
  }
];

// Property type configurations for UI
export const propertyTypeConfig = {
  residential: {
    label: "Residential",
    icon: "fa-home",
    color: "bg-blue-100 text-blue-800 border-blue-200",
    cardBorder: "border-l-blue-500"
  },
  rental: {
    label: "Rental",
    icon: "fa-key", 
    color: "bg-green-100 text-green-800 border-green-200",
    cardBorder: "border-l-green-500"
  },
  commercial: {
    label: "Commercial",
    icon: "fa-building",
    color: "bg-orange-100 text-orange-800 border-orange-200", 
    cardBorder: "border-l-orange-500"
  },
  lease: {
    label: "Lease",
    icon: "fa-handshake",
    color: "bg-purple-100 text-purple-800 border-purple-200",
    cardBorder: "border-l-purple-500"
  }
};

// NZ regions and suburbs for filtering
export const nzRegions = {
  auckland: {
    name: "Auckland",
    suburbs: ["Auckland Central", "Ponsonby", "Remuera", "Mount Eden", "Parnell", "Devonport", "Takapuna", "Henderson", "Manukau", "Botany"]
  },
  wellington: {
    name: "Wellington", 
    suburbs: ["Wellington Central", "Te Aro", "Mount Victoria", "Thorndon", "Kelburn", "Island Bay", "Newtown", "Johnsonville"]
  },
  christchurch: {
    name: "Christchurch",
    suburbs: ["Christchurch Central", "Riccarton", "Fendalton", "Merivale", "Papanui", "Sydenham", "Addington", "Cashmere"]
  },
  hamilton: {
    name: "Hamilton",
    suburbs: ["Hamilton Central", "Hillcrest", "Fairfield", "Te Rapa", "Chartwell", "Dinsdale"]
  },
  tauranga: {
    name: "Tauranga",
    suburbs: ["Mount Maunganui", "Papamoa", "Bethlehem", "Gate Pa", "Greerton"]
  },
  dunedin: {
    name: "Dunedin", 
    suburbs: ["North Dunedin", "South Dunedin", "Roslyn", "Maori Hill", "St Clair"]
  }
};
