// DEPRECATED: This function generates invalid PDFs and should NOT be used in production
// For legal documents, use proper PDF libraries like PDFKit, Puppeteer, or a PDF service
// This is a LEGAL LIABILITY - these documents are NOT legally valid PDFs

/**
 * @deprecated DO NOT USE - Generates invalid PDF structure
 * @throws Error Always throws to prevent usage
 */
export function generateOfferPDF(offer: any, property: any): string {
  throw new Error(
    "PDF generation is disabled. This function generates invalid PDFs that are not legally enforceable. " +
    "Use generateOfferHTML() instead and convert to PDF using a proper library like Puppeteer or a PDF service."
  );
  
  // Original fake PDF code removed to prevent accidental usage
  /* const pdfContent = `
%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 5 0 R
>>
>>
>>
endobj

4 0 obj
<<
/Length 2000
>>
stream
BT
/F1 16 Tf
50 750 Td
(PROPERTY PURCHASE OFFER) Tj
0 -30 Td
/F1 10 Tf
(Generated: ${new Date().toLocaleString()}) Tj
0 -40 Td
/F1 12 Tf
(PROPERTY DETAILS:) Tj
0 -20 Td
/F1 10 Tf
(Address: ${property.address}) Tj
0 -15 Td
(Lot Number: ${offer.propertyLotNumber}) Tj
0 -15 Td
(Certificate of Title: ${offer.propertyCertificateOfTitle}) Tj
0 -30 Td
/F1 12 Tf
(OFFER DETAILS:) Tj
0 -20 Td
/F1 10 Tf
(Offer Price: ${offer.offerPrice}) Tj
0 -15 Td
(Settlement Period: ${offer.settlementPeriod}) Tj
0 -15 Td
(Finance Condition: ${offer.financeCondition ? 'Yes' : 'No'}) Tj
0 -15 Td
(Building Inspection: ${offer.buildingInspectionCondition ? 'Yes' : 'No'}) Tj
0 -15 Td
(LIM Report: ${offer.limCondition ? 'Yes' : 'No'}) Tj
0 -30 Td
/F1 12 Tf
(BUYER INFORMATION:) Tj
0 -20 Td
/F1 10 Tf
(Name: ${offer.buyerName}) Tj
0 -15 Td
(Email: ${offer.buyerEmail}) Tj
0 -15 Td
(Phone: ${offer.buyerPhone}) Tj
0 -30 Td
/F1 12 Tf
(OFFER ID: ${offer.id}) Tj
0 -20 Td
/F1 8 Tf
(This document was generated by HouseMatch NZ) Tj
0 -10 Td
(Generated on: ${new Date().toISOString()}) Tj
ET
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000053 00000 n 
0000000110 00000 n 
0000000292 00000 n 
0000002350 00000 n 
trailer
<<
/Size 6
/Root 1 0 R
>>
startxref
2418
%%EOF
  `; */
  
  // Removed - this fake PDF is not legally valid
  // return Buffer.from(pdfContent, 'utf-8').toString('base64');
}

// Alternative: Generate HTML that can be converted to PDF
export function generateOfferHTML(offer: any, property: any): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Property Purchase Offer - ${offer.id}</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
            .section { margin-bottom: 25px; }
            .section h3 { color: #333; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
            .info-row { display: flex; margin-bottom: 8px; }
            .info-label { font-weight: bold; width: 200px; }
            .info-value { flex: 1; }
            .highlight { background: #f0f8ff; padding: 15px; border-left: 4px solid #007cba; }
            .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>PROPERTY PURCHASE OFFER</h1>
            <p><strong>Offer ID:</strong> ${offer.id}</p>
            <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        </div>

        <div class="section">
            <h3>PROPERTY DETAILS</h3>
            <div class="info-row">
                <div class="info-label">Address:</div>
                <div class="info-value">${property.address}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Lot Number:</div>
                <div class="info-value"><code>${offer.propertyLotNumber}</code></div>
            </div>
            <div class="info-row">
                <div class="info-label">Certificate of Title:</div>
                <div class="info-value"><code>${offer.propertyCertificateOfTitle}</code></div>
            </div>
            ${offer.propertyZoning ? `
            <div class="info-row">
                <div class="info-label">Zoning:</div>
                <div class="info-value">${offer.propertyZoning}</div>
            </div>
            ` : ''}
            ${offer.propertyLandArea ? `
            <div class="info-row">
                <div class="info-label">Land Area:</div>
                <div class="info-value">${offer.propertyLandArea}m²</div>
            </div>
            ` : ''}
        </div>

        <div class="section">
            <h3>OFFER DETAILS</h3>
            <div class="highlight">
                <div class="info-row">
                    <div class="info-label">Offer Price:</div>
                    <div class="info-value"><strong>${offer.offerPrice}</strong></div>
                </div>
            </div>
            <div class="info-row">
                <div class="info-label">Settlement Period:</div>
                <div class="info-value">${offer.settlementPeriod}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Finance Condition:</div>
                <div class="info-value">${offer.financeCondition ? '✓ Yes' : '✗ No'}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Building Inspection:</div>
                <div class="info-value">${offer.buildingInspectionCondition ? '✓ Yes' : '✗ No'}</div>
            </div>
            <div class="info-row">
                <div class="info-label">LIM Report:</div>
                <div class="info-value">${offer.limCondition ? '✓ Yes' : '✗ No'}</div>
            </div>
        </div>

        <div class="section">
            <h3>BUYER INFORMATION</h3>
            <div class="info-row">
                <div class="info-label">Name:</div>
                <div class="info-value">${offer.buyerName}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Email:</div>
                <div class="info-value">${offer.buyerEmail}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Phone:</div>
                <div class="info-value">${offer.buyerPhone}</div>
            </div>
        </div>

        ${offer.additionalConditions || offer.additionalComments ? `
        <div class="section">
            <h3>ADDITIONAL INFORMATION</h3>
            ${offer.additionalConditions ? `
            <div class="info-row">
                <div class="info-label">Additional Conditions:</div>
                <div class="info-value">${offer.additionalConditions}</div>
            </div>
            ` : ''}
            ${offer.additionalComments ? `
            <div class="info-row">
                <div class="info-label">Comments:</div>
                <div class="info-value">${offer.additionalComments}</div>
            </div>
            ` : ''}
        </div>
        ` : ''}

        <div class="footer">
            <p><strong>LEGAL NOTICE:</strong> This document contains an offer to purchase real estate. This offer is legally binding if accepted by the seller. All parties should seek independent legal advice before proceeding.</p>
            <p><strong>Generated by:</strong> HouseMatch NZ</p>
            <p><strong>Generated on:</strong> ${new Date().toISOString()}</p>
            <p><strong>Document ID:</strong> ${offer.id}</p>
        </div>
    </body>
    </html>
  `;
}

// Basic PDF generation using simple text format (for demonstration)
export function generateSimplePDF(offer: any, property: any): string {
  const content = `
PROPERTY PURCHASE OFFER
Document ID: ${offer.id}
Generated: ${new Date().toLocaleString()}

PROPERTY DETAILS:
Address: ${property.address}
Lot Number: ${offer.propertyLotNumber}
Certificate of Title: ${offer.propertyCertificateOfTitle}
${offer.propertyZoning ? `Zoning: ${offer.propertyZoning}` : ''}
${offer.propertyLandArea ? `Land Area: ${offer.propertyLandArea}m²` : ''}

OFFER DETAILS:
Offer Price: ${offer.offerPrice}
Settlement Period: ${offer.settlementPeriod}
Finance Condition: ${offer.financeCondition ? 'Yes' : 'No'}
Building Inspection: ${offer.buildingInspectionCondition ? 'Yes' : 'No'}
LIM Report: ${offer.limCondition ? 'Yes' : 'No'}

BUYER INFORMATION:
Name: ${offer.buyerName}
Email: ${offer.buyerEmail}
Phone: ${offer.buyerPhone}

${offer.additionalConditions ? `ADDITIONAL CONDITIONS:\n${offer.additionalConditions}\n` : ''}
${offer.additionalComments ? `COMMENTS:\n${offer.additionalComments}\n` : ''}

LEGAL NOTICE:
This document contains an offer to purchase real estate. This offer is 
legally binding if accepted by the seller. All parties should seek 
independent legal advice before proceeding.

Generated by: HouseMatch NZ
Generated on: ${new Date().toISOString()}
Document ID: ${offer.id}
  `;

  // Convert to base64 for email attachment (as a text file, in production use proper PDF library)
  return Buffer.from(content, 'utf-8').toString('base64');
}